In [5]:
!pip install netCDF4

Collecting netCDF4
  Downloading netCDF4-1.7.1.post2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting cftime (from netCDF4)
  Downloading cftime-1.6.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from netCDF4) (2024.8.30)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from netCDF4) (1.26.4)
Downloading netCDF4-1.7.1.post2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 47.8 MB/s eta 0:00:00
Downloading cftime-1.6.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 55.1 MB/s eta 0:00:00
Installing collected packages: cftime, netCDF4
Successfully installed cftime-1.6.4 netCDF4-1.7.1.post2

In [15]:
import netCDF4 as nc

# Carga el archivo .nc
archivo = '/humidity.nc'
ds = nc.Dataset(archivo)

# Explora las dimensiones y variables
print(ds)

# Para ver una lista de las variables del archivo
print(ds.variables.keys())

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    GRIB_centre: ecmf
    GRIB_centreDescription: European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre: 0
    Conventions: CF-1.7
    institution: European Centre for Medium-Range Weather Forecasts
    history: 2024-09-22T20:01 GRIB to CDM+CF via cfgrib-0.9.14.1/ecCodes-2.36.0 with {"source": "data.grib", "filter_by_keys": {}, "encode_cf": ["parameter", "time", "geography", "vertical"]}
    dimensions(sizes): date(372), pressure_level(1), latitude(19), longitude(17)
    variables(dimensions): int64 number(), int64 date(date), float64 pressure_level(pressure_level), float64 latitude(latitude), float64 longitude(longitude), <class 'str'> expver(date), float32 r(date, pressure_level, latitude, longitude)
    groups:
dict_keys(['number', 'date', 'pressure_level', 'latitude', 'longitude', 'expver', 'r'])

In [16]:
# Acceder a una variable específica
humidity = ds.variables['r'][:]  # Cambia 'nombre_de_variable_humedad' por el nombre exacto
print(humidity)

# Cierra el archivo
#ds.close()

[[[[0.0005349  0.00053438 0.00053391 ... 0.00052097 0.00052019
    0.00051923]
   [0.00052962 0.00052907 0.00052839 ... 0.00051545 0.00051457
    0.00051375]
   [0.00052413 0.00052359 0.00052288 ... 0.00051004 0.00050922
    0.00050826]
   ...
   [0.00044686 0.00044614 0.00044549 ... 0.00043804 0.00043732
    0.00043661]
   [0.00044161 0.0004409  0.00044018 ... 0.00043275 0.00043204
    0.00043129]
   [0.00043633 0.00043561 0.0004349  ... 0.00042744 0.00042659
    0.00042588]]]


 [[[0.00047637 0.00047642 0.00047652 ... 0.00047763 0.00047778
    0.00047791]
   [0.00047401 0.00047404 0.00047398 ... 0.00047456 0.00047478
    0.00047499]
   [0.00047116 0.00047111 0.00047101 ... 0.00047145 0.00047168
    0.00047192]
   ...
   [0.00041478 0.00041446 0.00041414 ... 0.00040935 0.00040903
    0.00040872]
   [0.00040884 0.00040848 0.00040811 ... 0.00040342 0.00040307
    0.0004027 ]
   [0.00040281 0.00040243 0.00040201 ... 0.00039742 0.00039711
    0.00039673]]]


 [[[0.00036403 0.00036444 0.00036486 ... 0.00036785 0.000368
    0.00036815]
   [0.00036233 0.00036275 0.00036315 ... 0.00036566 0.00036577
    0.00036583]
   [0.00036046 0.00036086 0.00036126 ... 0.00036319 0.00036322
    0.00036326]
   ...
   [0.00031926 0.00031949 0.00031972 ... 0.00032154 0.0003215
    0.00032139]
   [0.00031592 0.00031616 0.00031637 ... 0.00031764 0.00031759
    0.00031747]
   [0.00031253 0.00031273 0.00031292 ... 0.00031376 0.0003137
    0.00031359]]]


 ...


 [[[0.00028113 0.00028122 0.00028128 ... 0.00028165 0.00028168
    0.00028168]
   [0.00027992 0.00027998 0.00028001 ... 0.00028044 0.00028044
    0.00028043]
   [0.00027874 0.00027878 0.00027878 ... 0.00027922 0.00027924
    0.00027922]
   ...
   [0.00026713 0.00026713 0.00026713 ... 0.00026723 0.00026719
    0.00026719]
   [0.00026654 0.00026654 0.00026656 ... 0.00026667 0.00026667
    0.00026667]
   [0.000266   0.00026601 0.00026603 ... 0.0002662  0.0002662
    0.0002662 ]]]


 [[[0.00020208 0.00020225 0.00020245 ... 0.00020394 0.00020418
    0.00020441]
   [0.00020192 0.00020222 0.00020239 ... 0.00020396 0.00020419
    0.00020443]
   [0.00020191 0.00020217 0.00020241 ... 0.00020418 0.00020433
    0.00020457]
   ...
   [0.00020995 0.00021022 0.00021055 ... 0.00021441 0.00021474
    0.00021498]
   [0.00021104 0.00021131 0.00021164 ... 0.00021557 0.00021584
    0.00021617]
   [0.00021215 0.00021247 0.00021274 ... 0.0002167  0.00021704
    0.00021736]]]


 [[[0.00035377 0.0003531  0.00035245 ... 0.00034455 0.00034377
    0.00034288]
   [0.00034738 0.00034673 0.00034618 ... 0.00033852 0.00033764
    0.00033692]
   [0.000341   0.00034046 0.00033981 ... 0.00033239 0.00033168
    0.00033096]
   ...
   [0.00027346 0.00027318 0.00027294 ... 0.00026958 0.00026917
    0.00026886]
   [0.00027083 0.00027053 0.00027016 ... 0.00026706 0.00026675
    0.00026634]
   [0.00026829 0.00026805 0.00026781 ... 0.00026471 0.00026447
    0.00026417]]]]

In [17]:
tiempo = ds.variables['date'][:]

In [19]:
print(tiempo)

[19930101 19930201 19930301 19930401 19930501 19930601 19930701 19930801
 19930901 19931001 19931101 19931201 19940101 19940201 19940301 19940401
 19940501 19940601 19940701 19940801 19940901 19941001 19941101 19941201
 19950101 19950201 19950301 19950401 19950501 19950601 19950701 19950801
 19950901 19951001 19951101 19951201 19960101 19960201 19960301 19960401
 19960501 19960601 19960701 19960801 19960901 19961001 19961101 19961201
 19970101 19970201 19970301 19970401 19970501 19970601 19970701 19970801
 19970901 19971001 19971101 19971201 19980101 19980201 19980301 19980401
 19980501 19980601 19980701 19980801 19980901 19981001 19981101 19981201
 19990101 19990201 19990301 19990401 19990501 19990601 19990701 19990801
 19990901 19991001 19991101 19991201 20000101 20000201 20000301 20000401
 20000501 20000601 20000701 20000801 20000901 20001001 20001101 20001201
 20010101 20010201 20010301 20010401 20010501 20010601 20010701 20010801
 20010901 20011001 20011101 20011201 20020101 20020201 20020301 20020401
 20020501 20020601 20020701 20020801 20020901 20021001 20021101 20021201
 20030101 20030201 20030301 20030401 20030501 20030601 20030701 20030801
 20030901 20031001 20031101 20031201 20040101 20040201 20040301 20040401
 20040501 20040601 20040701 20040801 20040901 20041001 20041101 20041201
 20050101 20050201 20050301 20050401 20050501 20050601 20050701 20050801
 20050901 20051001 20051101 20051201 20060101 20060201 20060301 20060401
 20060501 20060601 20060701 20060801 20060901 20061001 20061101 20061201
 20070101 20070201 20070301 20070401 20070501 20070601 20070701 20070801
 20070901 20071001 20071101 20071201 20080101 20080201 20080301 20080401
 20080501 20080601 20080701 20080801 20080901 20081001 20081101 20081201
 20090101 20090201 20090301 20090401 20090501 20090601 20090701 20090801
 20090901 20091001 20091101 20091201 20100101 20100201 20100301 20100401
 20100501 20100601 20100701 20100801 20100901 20101001 20101101 20101201
 20110101 20110201 20110301 20110401 20110501 20110601 20110701 20110801
 20110901 20111001 20111101 20111201 20120101 20120201 20120301 20120401
 20120501 20120601 20120701 20120801 20120901 20121001 20121101 20121201
 20130101 20130201 20130301 20130401 20130501 20130601 20130701 20130801
 20130901 20131001 20131101 20131201 20140101 20140201 20140301 20140401
 20140501 20140601 20140701 20140801 20140901 20141001 20141101 20141201
 20150101 20150201 20150301 20150401 20150501 20150601 20150701 20150801
 20150901 20151001 20151101 20151201 20160101 20160201 20160301 20160401
 20160501 20160601 20160701 20160801 20160901 20161001 20161101 20161201
 20170101 20170201 20170301 20170401 20170501 20170601 20170701 20170801
 20170901 20171001 20171101 20171201 20180101 20180201 20180301 20180401
 20180501 20180601 20180701 20180801 20180901 20181001 20181101 20181201
 20190101 20190201 20190301 20190401 20190501 20190601 20190701 20190801
 20190901 20191001 20191101 20191201 20200101 20200201 20200301 20200401
 20200501 20200601 20200701 20200801 20200901 20201001 20201101 20201201
 20210101 20210201 20210301 20210401 20210501 20210601 20210701 20210801
 20210901 20211001 20211101 20211201 20220101 20220201 20220301 20220401
 20220501 20220601 20220701 20220801 20220901 20221001 20221101 20221201
 20230101 20230201 20230301 20230401 20230501 20230601 20230701 20230801
 20230901 20231001 20231101 20231201]

In [20]:
import pandas as pd
import numpy as np

In [22]:
humidity = ds.variables['r'][:]  # Tu array de humedad
date = ds.variables['date'][:]  # Tu array de fechas

In [23]:
fechas_legibles = pd.to_datetime(date.astype(str), format='%Y%m%d')

# Aplanar la variable de humedad para que coincida con las fechas
humidity_flat = humidity.reshape(humidity.shape[0], -1)

# Crear un DataFrame con las fechas y los valores de humedad
df = pd.DataFrame(humidity_flat, index=fechas_legibles)

# Renombrar las columnas del DataFrame si es necesario
df.columns = [f'Humedad_{i+1}' for i in range(humidity_flat.shape[1])]

# Mostrar el DataFrame resultante
print(df)

            Humedad_1  Humedad_2  Humedad_3  Humedad_4  Humedad_5  Humedad_6  \
1993-01-01   0.000535   0.000534   0.000534   0.000533   0.000533   0.000532
1993-02-01   0.000476   0.000476   0.000477   0.000477   0.000477   0.000477
1993-03-01   0.000364   0.000364   0.000365   0.000365   0.000366   0.000366
1993-04-01   0.000245   0.000245   0.000245   0.000246   0.000246   0.000246
1993-05-01   0.000209   0.000209   0.000209   0.000209   0.000209   0.000209
...               ...        ...        ...        ...        ...        ...
2023-08-01   0.000377   0.000377   0.000376   0.000376   0.000376   0.000376
2023-09-01   0.000252   0.000252   0.000253   0.000253   0.000252   0.000252
2023-10-01   0.000281   0.000281   0.000281   0.000281   0.000281   0.000281
2023-11-01   0.000202   0.000202   0.000202   0.000203   0.000203   0.000203
2023-12-01   0.000354   0.000353   0.000352   0.000352   0.000351   0.000351

            Humedad_7  Humedad_8  Humedad_9  Humedad_10  ...  Humedad_314  \
1993-01-01   0.000531   0.000529   0.000528    0.000526  ...     0.000432
1993-02-01   0.000477   0.000477   0.000477    0.000477  ...     0.000400
1993-03-01   0.000366   0.000367   0.000367    0.000367  ...     0.000314
1993-04-01   0.000246   0.000246   0.000247    0.000247  ...     0.000234
1993-05-01   0.000209   0.000209   0.000210    0.000210  ...     0.000214
...               ...        ...        ...         ...  ...          ...
2023-08-01   0.000376   0.000375   0.000374    0.000374  ...     0.000329
2023-09-01   0.000252   0.000252   0.000252    0.000252  ...     0.000228
2023-10-01   0.000281   0.000281   0.000281    0.000282  ...     0.000266
2023-11-01   0.000203   0.000203   0.000203    0.000203  ...     0.000214
2023-12-01   0.000350   0.000349   0.000349    0.000348  ...     0.000266

            Humedad_315  Humedad_316  Humedad_317  Humedad_318  Humedad_319  \
1993-01-01     0.000431     0.000431     0.000430     0.000430     0.000429
1993-02-01     0.000399     0.000399     0.000399     0.000398     0.000398
1993-03-01     0.000314     0.000314     0.000314     0.000314     0.000314
1993-04-01     0.000235     0.000235     0.000235     0.000235     0.000236
1993-05-01     0.000214     0.000214     0.000214     0.000214     0.000214
...                 ...          ...          ...          ...          ...
2023-08-01     0.000329     0.000329     0.000330     0.000330     0.000330
2023-09-01     0.000228     0.000228     0.000228     0.000228     0.000228
2023-10-01     0.000266     0.000266     0.000266     0.000266     0.000266
2023-11-01     0.000215     0.000215     0.000215     0.000216     0.000216
2023-12-01     0.000266     0.000266     0.000266     0.000265     0.000265

            Humedad_320  Humedad_321  Humedad_322  Humedad_323
1993-01-01     0.000428     0.000427     0.000427     0.000426
1993-02-01     0.000398     0.000397     0.000397     0.000397
1993-03-01     0.000314     0.000314     0.000314     0.000314
1993-04-01     0.000236     0.000236     0.000236     0.000237
1993-05-01     0.000214     0.000214     0.000215     0.000215
...                 ...          ...          ...          ...
2023-08-01     0.000331     0.000331     0.000330     0.000330
2023-09-01     0.000228     0.000228     0.000228     0.000228
2023-10-01     0.000266     0.000266     0.000266     0.000266
2023-11-01     0.000216     0.000217     0.000217     0.000217
2023-12-01     0.000265     0.000265     0.000264     0.000264

[372 rows x 323 columns]

In [24]:
df.head()

,Humedad_1,Humedad_2,Humedad_3,Humedad_4,Humedad_5,Humedad_6,Humedad_7,Humedad_8,Humedad_9,Humedad_10,...,Humedad_314,Humedad_315,Humedad_316,Humedad_317,Humedad_318,Humedad_319,Humedad_320,Humedad_321,Humedad_322,Humedad_323
1993-01-01,0.000535,0.000534,0.000534,0.000533,0.000533,0.000532,0.000531,0.000529,0.000528,0.000526,...,0.000432,0.000431,0.000431,0.000430,0.000430,0.000429,0.000428,0.000427,0.000427,0.000426
1993-02-01,0.000476,0.000476,0.000477,0.000477,0.000477,0.000477,0.000477,0.000477,0.000477,0.000477,...,0.000400,0.000399,0.000399,0.000399,0.000398,0.000398,0.000398,0.000397,0.000397,0.000397
1993-03-01,0.000364,0.000364,0.000365,0.000365,0.000366,0.000366,0.000366,0.000367,0.000367,0.000367,...,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314,0.000314
1993-04-01,0.000245,0.000245,0.000245,0.000246,0.000246,0.000246,0.000246,0.000246,0.000247,0.000247,...,0.000234,0.000235,0.000235,0.000235,0.000235,0.000236,0.000236,0.000236,0.000236,0.000237
1993-05-01,0.000209,0.000209,0.000209,0.000209,0.000209,0.000209,0.000209,0.000209,0.000210,0.000210,...,0.000214,0.000214,0.000214,0.000214,0.000214,0.000214,0.000214,0.000214,0.000215,0.000215

In [25]:
print(humidity.shape)

(372, 1, 19, 17)

In [26]:
# Ver las coordenadas de latitud y longitud
latitudes = ds.variables['latitude'][:]
longitudes = ds.variables['longitude'][:]

print("Latitudes:", latitudes)
print("Longitudes:", longitudes)

Latitudes: [26.96 26.71 26.46 26.21 25.96 25.71 25.46 25.21 24.96 24.71 24.46 24.21
 23.96 23.71 23.46 23.21 22.96 22.71 22.46]
Longitudes: [-109.43 -109.18 -108.93 -108.68 -108.43 -108.18 -107.93 -107.68 -107.43
 -107.18 -106.93 -106.68 -106.43 -106.18 -105.93 -105.68 -105.43]

In [30]:
presion = ds.variables['pressure_level'][:]
print("niveles de presion:", presion)

niveles de presion: [1.]

-----------------

In [31]:
# Elige el índice de latitud y longitud que desees
lat_index = 0  # Cambia esto al índice de latitud que desees (0-18)
lon_index = 0  # Cambia esto al índice de longitud que desees (0-16)

# Seleccionar la humedad en el punto específico (con solo un nivel de presión)
humedad_punto = ds.variables['r'][:, 0, lat_index, lon_index]  # [date, pressure_level, latitude, longitude]

# Convertir a un formato unidimensional
humedad_punto = humedad_punto.flatten()

# Crear el DataFrame
df = pd.DataFrame({
    'Fecha': fechas_legibles,
    'Humedad': humedad_punto
})

# Asegúrate de que la longitud de 'Humedad' y 'Fecha' coincida
print("Tamaño de Humedad:", humedad_punto.shape)
print("Tamaño de Fechas:", len(fechas_legibles))

# Establecer la fecha como índice del DataFrame
df.set_index('Fecha', inplace=True)

# Mostrar el DataFrame
print(df)

Tamaño de Humedad: (372,)
Tamaño de Fechas: 372
             Humedad
Fecha
1993-01-01  0.000535
1993-02-01  0.000476
1993-03-01  0.000364
1993-04-01  0.000245
1993-05-01  0.000209
...              ...
2023-08-01  0.000377
2023-09-01  0.000252
2023-10-01  0.000281
2023-11-01  0.000202
2023-12-01  0.000354

[372 rows x 1 columns]

In [34]:
# Seleccionar la humedad para todas las latitudes y longitudes
humedad_area = ds.variables['r'][:, 0, :, :]  # Esto selecciona todas las fechas, 1 nivel de presión, todas las latitudes y longitudes

# Verifica la forma del array de humedad
print("Forma de humedad_area:", humedad_area.shape)  # Debe ser (372, 19, 17)

# Promedia sobre las dimensiones de latitud y longitud (2 y 3)
humedad_promedio = humedad_area.mean(axis=(1, 2))  # Promedio sobre latitud y longitud
humedad_promedio = humedad_promedio.flatten()  # Esto convierte la humedad a un array unidimensional

# Crear el DataFrame para el promedio
df_promedio = pd.DataFrame({
    'Fecha': fechas_legibles,
    'Humedad_Promedio': humedad_promedio
})

# Establecer la fecha como índice
df_promedio.set_index('Fecha', inplace=True)

# Mostrar el DataFrame
print(df_promedio)

Forma de humedad_area: (372, 19, 17)
            Humedad_Promedio
Fecha
1993-01-01          0.000479
1993-02-01          0.000444
1993-03-01          0.000342
1993-04-01          0.000241
1993-05-01          0.000212
...                      ...
2023-08-01          0.000353
2023-09-01          0.000239
2023-10-01          0.000273
2023-11-01          0.000207
2023-12-01          0.000302

[372 rows x 1 columns]

In [35]:
# Guardar el DataFrame en un archivo de texto (.txt)
df_promedio.to_csv('humedad_promedio.txt', sep='\t', index=True)  # sep='\t' para tabulaciones